image: Visual Studio 2019
version: '{branch}-{build}'
environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install parse"

build: off

test_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install ."

after_test:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python scripts\\winpackage.py"

artifacts:
  - path: "*.zip"

