image: Visual Studio 2019
version: '{branch}-{build}'
environment:
  matrix:
    - PY: "-3.7"
    - PY: "-3.7-x64"
    - PY: "-3.8"
    - PY: "-3.8-x64"
    - PY: "-3.9"
    - PY: "-3.9-x64"

install:
  - "py %PYTHON% -m pip install parse"

build: off

test_script:
  - "py %PYTHON% -m pip install ."

after_test:
  - "py %PYTHON% -m pip scripts\\winpackage.py"

artifacts:
  - path: "*.zip"

