image: Visual Studio 2019
version: '{branch}-{build}'
environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install parse wheel"

build: off

test_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install ."

after_test:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python scripts\\winpackage.py"

artifacts:
  - path: "*.zip"

deploy:
  description: 'Release version $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure: R2zEjDNRq2HLt+v9fwQvNVV6FDkxBmF7AD4GEqRepr8NjZRRDUBGcaimr+tkeAlO
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true