environment:
  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install:
  - "%PYTHON%\\python.exe -m pip install parse"
  - "%PYTHON%\\python.exe -m pip install wheel . -v"

build: 
  - "%PYTHON%\\python.exe scripts\\winpackage.py"

#test_script:
#  - "%PYTHON%\\python.exe test.py"

#after_test:
#  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: *.zip